"""empty message

Revision ID: 528605de96c6
Revises: 10bed27fedfa
Create Date: 2019-10-27 14:38:23.372923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528605de96c6'
down_revision = '10bed27fedfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_of_life_cell', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_of_life_cell', 'color')
    # ### end Alembic commands ###
