"""empty message

Revision ID: 820433883d5d
Revises: 2ec3f4bbf368
Create Date: 2019-10-20 11:02:30.558409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820433883d5d'
down_revision = '2ec3f4bbf368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
